- init:
    assign:
      - namespaces: '307575647034'
      - project: $${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - service_name: 'dev-serverless-dbt-run-2'
- dbt_cloud_run_1_task:
    call: http.get
    args:
      url:  https://dev-serverless-dbt-run-1-jrek4srhha-ew.a.run.app
      auth:
        type: OIDC
    result: response
- dbt_cloud_run_2_task:
    try:
      call: http.get
      args:
        url: https://dev-serverless-dbt-run-2-jrek4srhha-ew.a.run.app
        auth:
          type: OIDC
      result: apiResponse
    retry: $${http.default_retry}
