## project name should be lower case and underscored only.
## good name should reflect org name and intended use of the models

#name: 'my_snowflake_db'
name: 'dbt_poc'
version: 1.0.7
config-version: 2

# this setting configures which 'profile' dbt uses for this project
profile: 'dbt_poc'

## these configurations specify where dbt should look for files.
## e.g. the source paths config states the models are in "models/" dir.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target  ## where to store the compiled SQL files
clean-targets:           ## directories to be removed by `dbt clean`
  - target
  - dbt_modules


## configuring models
## full docs https://docs.getdbt.com/docs/configuring-models

## in this example, we tell dbt to build all models in the `example/` dir as tables
## These settings can be overridden in the individual model files using the
## `{{ config(...) }}` macro
models:
  dbt_poc:
    +materialized: table
