#Using dbt website to configure snowflake profile
my_snowflake_db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_ACCOUNT') }}"

#user/password auth
      user: "{{ env_var('DBT_ENV_SECRET_DBT_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_DBT_PASSWORD') }}"

      role: ACCOUNTADMIN
      database: dbt_cloud_run_1
      warehouse: DBT_DEMO
      schema: ./models/example/schema.yml
      threads: 4
      client_session_keep_alive: False
      query_tag: profitability_tool_DOA_dev

#optional
      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False


# demo profiles yaml from the blog post
#dbt_poc:  # profile name from dbt_project.yml
#  target: dev
#  outputs:
#
#    dev:
#      type: bigquery
#      method: oauth
#      project: silver-antonym-326607
#      dataset: dbt_poc_test
#      threads: 4
#      timeout_seconds: 300
#      priority: interactive
#      retries: 1

#    prod:
#      type: bigquery
#      method: oauth
#      project: silver-antonym-326607
#      dataset: dbt_poc_prod
#      threads: 4
#      timeout_seconds: 300
#      priority: interactive
#      retries: 1
